--
-- PostgreSQL database dump
--

\restrict TPq7EMbEtV5lWr9PahhCTYBKw93mykwCQUeO6cTJNCGxMzJoLjIUJPWWXmdABdC

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg12+2)
-- Dumped by pg_dump version 18.1 (Ubuntu 18.1-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: lauri11
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO lauri11;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO lauri11;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO lauri11;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO lauri11;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_bloqueo; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_bloqueo (
    id bigint NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone,
    hora_fin time without time zone,
    motivo character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    cancha_id bigint,
    complejo_id bigint NOT NULL,
    created_by_id bigint
);


ALTER TABLE public.core_bloqueo OWNER TO lauri11;

--
-- Name: core_bloqueo_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_bloqueo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_bloqueo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_cancha; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_cancha (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    precio_hora numeric(10,2) NOT NULL,
    capacidad integer NOT NULL,
    descripcion text,
    imagen character varying(100),
    activa boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    complejo_id bigint NOT NULL,
    duracion_turno_minutos integer,
    CONSTRAINT core_cancha_capacidad_check CHECK ((capacidad >= 0)),
    CONSTRAINT core_cancha_duracion_turno_minutos_check CHECK ((duracion_turno_minutos >= 0))
);


ALTER TABLE public.core_cancha OWNER TO lauri11;

--
-- Name: core_cancha_caracteristicas; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_cancha_caracteristicas (
    id bigint NOT NULL,
    cancha_id bigint NOT NULL,
    caracteristicacancha_id bigint NOT NULL
);


ALTER TABLE public.core_cancha_caracteristicas OWNER TO lauri11;

--
-- Name: core_cancha_caracteristicas_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_cancha_caracteristicas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_cancha_caracteristicas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_cancha_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_cancha ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_cancha_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_caracteristicacancha; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_caracteristicacancha (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    icono character varying(50)
);


ALTER TABLE public.core_caracteristicacancha OWNER TO lauri11;

--
-- Name: core_caracteristicacancha_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_caracteristicacancha ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_caracteristicacancha_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_complejo; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_complejo (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion character varying(255) NOT NULL,
    telefono character varying(20),
    email character varying(254),
    logo character varying(100),
    hora_apertura time without time zone NOT NULL,
    hora_cierre time without time zone NOT NULL,
    activo boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    slug character varying(50) NOT NULL,
    subdominio character varying(50),
    direccion_detallada text,
    instagram character varying(100),
    twitter_x character varying(100)
);


ALTER TABLE public.core_complejo OWNER TO lauri11;

--
-- Name: core_complejo_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_complejo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_complejo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_creditocliente; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_creditocliente (
    id bigint NOT NULL,
    monto numeric(10,2) NOT NULL,
    monto_usado numeric(10,2) NOT NULL,
    motivo character varying(200) NOT NULL,
    activo boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    complejo_id bigint NOT NULL,
    turno_origen_id bigint,
    usuario_id bigint NOT NULL,
    creado_por_id bigint,
    modificado_por_id bigint,
    historial jsonb NOT NULL
);


ALTER TABLE public.core_creditocliente OWNER TO lauri11;

--
-- Name: core_creditocliente_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_creditocliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_creditocliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_integracionmercadopago; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_integracionmercadopago (
    id bigint NOT NULL,
    access_token character varying(255) NOT NULL,
    public_key character varying(255) NOT NULL,
    modo character varying(10) NOT NULL,
    activo boolean NOT NULL,
    webhook_secret character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    complejo_id bigint NOT NULL
);


ALTER TABLE public.core_integracionmercadopago OWNER TO lauri11;

--
-- Name: core_integracionmercadopago_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_integracionmercadopago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_integracionmercadopago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_preferenciascomplejo; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_preferenciascomplejo (
    id bigint NOT NULL,
    color_primario character varying(7) NOT NULL,
    color_secundario character varying(7) NOT NULL,
    color_fondo character varying(7) NOT NULL,
    sistema_ranking boolean NOT NULL,
    pago_senia boolean NOT NULL,
    turnos_fijos_habilitados boolean NOT NULL,
    cancelacion_online boolean NOT NULL,
    notificaciones_whatsapp boolean NOT NULL,
    notificaciones_email boolean NOT NULL,
    tiempo_minimo_cancelacion integer NOT NULL,
    tiempo_maximo_reserva integer NOT NULL,
    complejo_id bigint NOT NULL,
    duracion_turno_minutos integer NOT NULL,
    minutos_expiracion_pago integer NOT NULL,
    CONSTRAINT core_preferenciascomplejo_duracion_turno_minutos_check CHECK ((duracion_turno_minutos >= 0)),
    CONSTRAINT core_preferenciascomplejo_minutos_expiracion_pago_check CHECK ((minutos_expiracion_pago >= 0)),
    CONSTRAINT core_preferenciascomplejo_tiempo_maximo_reserva_check CHECK ((tiempo_maximo_reserva >= 0)),
    CONSTRAINT core_preferenciascomplejo_tiempo_minimo_cancelacion_check CHECK ((tiempo_minimo_cancelacion >= 0))
);


ALTER TABLE public.core_preferenciascomplejo OWNER TO lauri11;

--
-- Name: core_preferenciascomplejo_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_preferenciascomplejo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_preferenciascomplejo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_turno; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_turno (
    id bigint NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    estado character varying(20) NOT NULL,
    precio_total numeric(10,2) NOT NULL,
    senia_pagada numeric(10,2) NOT NULL,
    notas text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cancha_id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    creditos_usados numeric(10,2) NOT NULL,
    duracion_minutos integer NOT NULL,
    expira_en timestamp with time zone,
    pago_referencia character varying(100),
    senia_requerida numeric(10,2) NOT NULL,
    CONSTRAINT core_turno_duracion_minutos_check CHECK ((duracion_minutos >= 0))
);


ALTER TABLE public.core_turno OWNER TO lauri11;

--
-- Name: core_turno_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_turno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_turno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_turnofijo; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_turnofijo (
    id bigint NOT NULL,
    dia_semana integer NOT NULL,
    hora_inicio time without time zone NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    activo boolean NOT NULL,
    notas text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cancha_id bigint NOT NULL,
    cliente_id bigint NOT NULL
);


ALTER TABLE public.core_turnofijo OWNER TO lauri11;

--
-- Name: core_turnofijo_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_turnofijo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_turnofijo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_usuario; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_usuario (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    rol character varying(20) NOT NULL,
    dni character varying(20),
    celular character varying(20),
    direccion character varying(255),
    complejo_id bigint
);


ALTER TABLE public.core_usuario OWNER TO lauri11;

--
-- Name: core_usuario_groups; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_usuario_groups (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.core_usuario_groups OWNER TO lauri11;

--
-- Name: core_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_usuario_user_permissions; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.core_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.core_usuario_user_permissions OWNER TO lauri11;

--
-- Name: core_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.core_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO lauri11;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO lauri11;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO lauri11;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO lauri11;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: lauri11
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO lauri11;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: lauri11
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Usuario	6	add_usuario
22	Can change Usuario	6	change_usuario
23	Can delete Usuario	6	delete_usuario
24	Can view Usuario	6	view_usuario
25	Can add Característica de Cancha	7	add_caracteristicacancha
26	Can change Característica de Cancha	7	change_caracteristicacancha
27	Can delete Característica de Cancha	7	delete_caracteristicacancha
28	Can view Característica de Cancha	7	view_caracteristicacancha
29	Can add Complejo	8	add_complejo
30	Can change Complejo	8	change_complejo
31	Can delete Complejo	8	delete_complejo
32	Can view Complejo	8	view_complejo
33	Can add Preferencias de Complejo	9	add_preferenciascomplejo
34	Can change Preferencias de Complejo	9	change_preferenciascomplejo
35	Can delete Preferencias de Complejo	9	delete_preferenciascomplejo
36	Can view Preferencias de Complejo	9	view_preferenciascomplejo
37	Can add Cancha	10	add_cancha
38	Can change Cancha	10	change_cancha
39	Can delete Cancha	10	delete_cancha
40	Can view Cancha	10	view_cancha
41	Can add Administrador de Complejo	11	add_administradorcomplejo
42	Can change Administrador de Complejo	11	change_administradorcomplejo
43	Can delete Administrador de Complejo	11	delete_administradorcomplejo
44	Can view Administrador de Complejo	11	view_administradorcomplejo
45	Can add Turno Fijo	12	add_turnofijo
46	Can change Turno Fijo	12	change_turnofijo
47	Can delete Turno Fijo	12	delete_turnofijo
48	Can view Turno Fijo	12	view_turnofijo
49	Can add Turno	13	add_turno
50	Can change Turno	13	change_turno
51	Can delete Turno	13	delete_turno
52	Can view Turno	13	view_turno
53	Can add Bloqueo	14	add_bloqueo
54	Can change Bloqueo	14	change_bloqueo
55	Can delete Bloqueo	14	delete_bloqueo
56	Can view Bloqueo	14	view_bloqueo
57	Can add Crédito de Cliente	15	add_creditocliente
58	Can change Crédito de Cliente	15	change_creditocliente
59	Can delete Crédito de Cliente	15	delete_creditocliente
60	Can view Crédito de Cliente	15	view_creditocliente
61	Can add Integración Mercado Pago	16	add_integracionmercadopago
62	Can change Integración Mercado Pago	16	change_integracionmercadopago
63	Can delete Integración Mercado Pago	16	delete_integracionmercadopago
64	Can view Integración Mercado Pago	16	view_integracionmercadopago
65	Can add site	17	add_site
66	Can change site	17	change_site
67	Can delete site	17	delete_site
68	Can view site	17	view_site
\.


--
-- Data for Name: core_bloqueo; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_bloqueo (id, fecha, hora_inicio, hora_fin, motivo, created_at, cancha_id, complejo_id, created_by_id) FROM stdin;
3	2026-01-03	\N	\N	enzo	2025-12-27 23:58:06.72674+00	\N	1	\N
5	2026-01-23	\N	\N	Bloqueo por staff	2025-12-30 02:31:05.462596+00	\N	1	\N
\.


--
-- Data for Name: core_cancha; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_cancha (id, nombre, precio_hora, capacidad, descripcion, imagen, activa, created_at, updated_at, complejo_id, duracion_turno_minutos) FROM stdin;
2	Blindex	18000.00	4	Cancha afuéra al sol		t	2025-12-26 04:29:27.242143+00	2025-12-28 13:47:23.734329+00	1	60
1	Blindex 2	18000.00	4	asdasd		t	2025-12-25 16:16:49.311954+00	2025-12-28 13:47:23.736146+00	1	60
3	Cancha interior	15000.00	4	Cancha interior con aire		f	2025-12-26 04:29:46.270998+00	2025-12-28 13:47:23.737766+00	1	60
\.


--
-- Data for Name: core_cancha_caracteristicas; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_cancha_caracteristicas (id, cancha_id, caracteristicacancha_id) FROM stdin;
1	2	3
2	2	5
3	1	2
4	1	4
\.


--
-- Data for Name: core_caracteristicacancha; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_caracteristicacancha (id, nombre, icono) FROM stdin;
1	Interior	\N
2	Exterior	\N
3	Aire	\N
4	Cemento	\N
5	Sintetica	\N
6	Blindex	\N
\.


--
-- Data for Name: core_complejo; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_complejo (id, nombre, direccion, telefono, email, logo, hora_apertura, hora_cierre, activo, created_at, updated_at, slug, subdominio, direccion_detallada, instagram, twitter_x) FROM stdin;
1	Padel Point	Azcuenaga 1555	2325688709	asd@gmail.com		08:00:00	23:00:00	t	2025-12-25 16:16:22.142905+00	2025-12-28 14:25:54.891511+00	padel-point	padel-point		padeelpoint	\N
\.


--
-- Data for Name: core_creditocliente; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_creditocliente (id, monto, monto_usado, motivo, activo, created_at, updated_at, complejo_id, turno_origen_id, usuario_id, creado_por_id, modificado_por_id, historial) FROM stdin;
27	150000.00	14750.00	Crédito inicial de bienvenida (temporal para tests)	t	2025-12-27 14:14:28.135265+00	2025-12-27 14:15:04.745731+00	1	\N	36	\N	\N	[]
78	150000.00	0.00	Crédito inicial de bienvenida (temporal para tests)	t	2026-01-01 19:58:37.859817+00	2026-01-01 19:58:37.859834+00	1	\N	65	\N	\N	[{"fecha": "2026-01-01T19:58:37.852848+00:00", "monto": "150000.00", "accion": "creado", "motivo": "Crédito inicial de bienvenida (temporal para tests)", "creado_por": "sistema", "turno_origen_id": null}]
36	150000.00	10000.00	Crédito inicial de bienvenida (temporal para tests)	t	2025-12-27 19:49:07.275357+00	2025-12-27 19:50:34.173314+00	1	\N	41	\N	\N	[]
37	5000.00	0.00	Cancelación turno Cancha Afuéra - 27/12/2025 21:00	t	2025-12-27 19:51:00.594718+00	2025-12-27 19:51:00.594733+00	1	58	41	\N	\N	[]
39	6000.00	0.00	Cancelación turno Cancha Blindex - 27/12/2025 22:00	t	2025-12-27 23:38:07.483453+00	2025-12-27 23:38:07.483466+00	1	63	42	\N	\N	[]
40	150000.00	6000.00	Crédito inicial de bienvenida (temporal para tests)	t	2025-12-27 23:50:41.747692+00	2025-12-27 23:51:33.364833+00	1	\N	43	\N	\N	[]
41	6000.00	0.00	Cancelación turno Cancha Blindex - 28/12/2025 08:00	t	2025-12-27 23:51:46.766585+00	2025-12-27 23:51:46.766595+00	1	64	43	\N	\N	[]
42	5000.00	0.00	Cancelación turno Cancha Afuera - 29/12/2025 08:00	t	2025-12-27 23:53:17.120224+00	2025-12-27 23:53:17.120234+00	1	65	42	\N	\N	[]
38	150000.00	17000.00	Crédito inicial de bienvenida (temporal para tests)	t	2025-12-27 23:36:33.115479+00	2025-12-27 23:57:51.794727+00	1	\N	42	\N	\N	[]
43	6000.00	0.00	Bloqueo: Cancha Blindex 03/01/2026 08:00	t	2025-12-27 23:58:06.734449+00	2025-12-27 23:58:06.734465+00	1	67	42	\N	\N	[]
79	150000.00	4500.00	Crédito inicial de bienvenida (temporal para tests)	t	2026-01-01 20:18:24.482987+00	2026-01-01 20:20:11.668162+00	1	\N	66	\N	\N	[{"fecha": "2026-01-01T20:18:24.470599+00:00", "monto": "150000.00", "accion": "creado", "motivo": "Crédito inicial de bienvenida (temporal para tests)", "creado_por": "sistema", "turno_origen_id": null}, {"fecha": "2026-01-01T20:20:11.661645+00:00", "accion": "aplicado", "monto_aplicado": "4500.00", "monto_usado_nuevo": "4500.00", "monto_usado_anterior": "0.00"}, {"fecha": "2026-01-01T20:20:11.667926+00:00", "accion": "modificado", "cambios": {"monto_usado": {"nuevo": "4500.00", "anterior": "0.00"}}, "modificado_por": "sistema"}]
80	150000.00	0.00	Crédito inicial de bienvenida (temporal para tests)	t	2026-01-02 16:13:28.142865+00	2026-01-02 16:13:28.142882+00	1	\N	67	\N	\N	[{"fecha": "2026-01-02T16:13:28.135629+00:00", "monto": "150000.00", "accion": "creado", "motivo": "Crédito inicial de bienvenida (temporal para tests)", "creado_por": "sistema", "turno_origen_id": null}]
68	4500.00	0.00	Bloqueo: Blindex 30/12/2025 08:00	t	2025-12-28 15:15:55.906643+00	2025-12-28 15:15:55.906655+00	1	93	52	\N	\N	[]
67	150000.00	9000.00	Crédito inicial de bienvenida (temporal para tests)	t	2025-12-28 15:08:03.693053+00	2025-12-28 17:20:22.248865+00	1	\N	52	\N	\N	[]
70	4500.00	0.00	Cancelación por staff - Turno Blindex 2 - 29/12/2025 08:00	t	2025-12-29 15:46:01.649887+00	2025-12-29 15:46:01.649901+00	1	98	52	\N	\N	[]
76	150000.00	0.00	Crédito inicial de bienvenida (temporal para tests)	t	2025-12-30 15:18:29.744896+00	2025-12-30 15:18:29.744916+00	1	\N	58	\N	\N	[{"fecha": "2025-12-30T15:18:29.536369+00:00", "monto": "150000.00", "accion": "creado", "motivo": "Crédito inicial de bienvenida (temporal para tests)", "creado_por": "sistema", "turno_origen_id": null}]
77	150000.00	0.00	Crédito inicial de bienvenida (temporal para tests)	t	2026-01-01 19:45:19.125364+00	2026-01-01 19:45:19.12539+00	1	\N	64	\N	\N	[{"fecha": "2026-01-01T19:45:19.038348+00:00", "monto": "150000.00", "accion": "creado", "motivo": "Crédito inicial de bienvenida (temporal para tests)", "creado_por": "sistema", "turno_origen_id": null}]
\.


--
-- Data for Name: core_integracionmercadopago; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_integracionmercadopago (id, access_token, public_key, modo, activo, webhook_secret, created_at, updated_at, complejo_id) FROM stdin;
\.


--
-- Data for Name: core_preferenciascomplejo; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_preferenciascomplejo (id, color_primario, color_secundario, color_fondo, sistema_ranking, pago_senia, turnos_fijos_habilitados, cancelacion_online, notificaciones_whatsapp, notificaciones_email, tiempo_minimo_cancelacion, tiempo_maximo_reserva, complejo_id, duracion_turno_minutos, minutos_expiracion_pago) FROM stdin;
1	#3B82F6	#1E40AF	#F3F4F6	f	t	t	f	f	f	4	7	1	60	10
\.


--
-- Data for Name: core_turno; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_turno (id, fecha, hora_inicio, estado, precio_total, senia_pagada, notas, created_at, updated_at, cancha_id, cliente_id, creditos_usados, duracion_minutos, expira_en, pago_referencia, senia_requerida) FROM stdin;
114	2026-01-06	08:00:00	pendiente_pago	18000.00	4500.00	\N	2026-01-01 20:20:11.670837+00	2026-01-01 20:20:11.670849+00	2	66	4500.00	60	\N	\N	4500.00
57	2026-01-14	08:00:00	pendiente_pago	20000.00	5000.00	\N	2025-12-27 19:50:19.583904+00	2025-12-27 19:50:19.583918+00	2	41	5000.00	60	\N	\N	5000.00
58	2025-12-27	21:00:00	cancelado_usuario	20000.00	5000.00	\N	2025-12-27 19:50:34.175057+00	2025-12-27 19:51:00.59173+00	2	41	5000.00	60	\N	\N	5000.00
63	2025-12-27	22:00:00	cancelado_usuario	24000.00	6000.00	\N	2025-12-27 23:37:50.498483+00	2025-12-27 23:38:07.480304+00	1	42	6000.00	60	\N	\N	6000.00
64	2025-12-28	08:00:00	cancelado_usuario	24000.00	6000.00	\N	2025-12-27 23:51:33.366582+00	2025-12-27 23:51:46.763749+00	1	43	6000.00	60	\N	\N	6000.00
65	2025-12-29	08:00:00	cancelado_usuario	20000.00	5000.00	\N	2025-12-27 23:52:49.017209+00	2025-12-27 23:53:17.117303+00	2	42	5000.00	60	\N	\N	5000.00
67	2026-01-03	08:00:00	cancelado_admin	24000.00	6000.00	\N	2025-12-27 23:57:51.796553+00	2025-12-27 23:58:06.731269+00	1	42	6000.00	60	\N	\N	6000.00
49	2025-12-27	12:00:00	jugado	20000.00	5000.00	\N	2025-12-27 14:14:56.719146+00	2025-12-27 14:14:56.719157+00	2	36	5000.00	60	\N	\N	5000.00
51	2025-12-27	12:00:00	jugado	15000.00	3750.00	\N	2025-12-27 14:15:04.747101+00	2025-12-27 14:15:04.747108+00	3	36	3750.00	60	\N	\N	3750.00
50	2025-12-27	12:00:00	jugado	24000.00	6000.00	\N	2025-12-27 14:15:00.835491+00	2025-12-27 14:15:00.835496+00	1	36	6000.00	60	\N	\N	6000.00
93	2025-12-30	08:00:00	cancelado_admin	18000.00	4500.00	\N	2025-12-28 15:09:51.140058+00	2025-12-28 15:15:55.901373+00	2	52	4500.00	60	\N	\N	4500.00
98	2025-12-29	08:00:00	cancelado_admin	18000.00	4500.00	\N	2025-12-28 17:20:22.250397+00	2025-12-29 15:46:01.646696+00	1	52	4500.00	60	\N	\N	4500.00
\.


--
-- Data for Name: core_turnofijo; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_turnofijo (id, dia_semana, hora_inicio, fecha_inicio, fecha_fin, activo, notas, created_at, updated_at, cancha_id, cliente_id) FROM stdin;
\.


--
-- Data for Name: core_usuario; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_usuario (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, rol, dni, celular, direccion, complejo_id) FROM stdin;
36	pbkdf2_sha256$600000$IIiRuTqL8HGqgkwRq6siab$NOw8V5cbBuJOyTbGkwzlgyWuBcDsYS6Hcm6yU70AWM0=	2025-12-27 14:14:28.142797+00	f	Juanp 	Juan	P	juanpavone1@hotmail.com	f	t	2025-12-27 14:14:27.937226+00	cliente	\N	2273404354	\N	1
58	pbkdf2_sha256$600000$t3Pz5L99Pn5Tfj4FyeT8aC$xK6ih4ufD6mOyGyqwNHLCYOn7Nig+MGczGxgP7JY8qg=	2025-12-30 15:18:29.934192+00	f	LucasK	lucas	kastelan	kastelanlucas11@gmail.com	f	t	2025-12-30 15:18:28.048929+00	cliente	39963485	2325688709		1
41	pbkdf2_sha256$600000$XRYi6fIO4K99Adg7EOiNfn$M35FejsTQhaiCQt8Qmv6gjXn9hNKfCzkkdgVxDIoxBo=	2025-12-27 19:49:07.284485+00	f	nicoburgio.nb@gmail.com	nico	hhg	nicoburgio.nb@gmail.com	f	t	2025-12-27 19:49:06.044806+00	cliente		2325		1
42	pbkdf2_sha256$600000$cOFys2LDOnjgTBDEDdvwQX$Hst4oK3TUpVRffSA2/H9JJNJ5GxUkitcPdZ5k7zh46k=	2025-12-27 23:36:33.151093+00	f	Enzo86	Enzo	Costantino	enzocostantino@live.com.ar	f	t	2025-12-27 23:36:31.642408+00	cliente	43980643	2273404840		1
43	pbkdf2_sha256$600000$IUnBzmXNqN2kNGYvkSbQzc$gpKBLwcLSjo2HX8NeskObhqDxB9jdS4RWqOp5EHpYng=	2025-12-27 23:50:41.757106+00	f	Franzanotti 	Fran	Zanotti	franciscozanotti2013@hotmail.com	f	t	2025-12-27 23:50:40.3402+00	cliente	43732823	2273412686	Paso, 715, Carmen de areco	1
52	pbkdf2_sha256$600000$u5uNrSoyKBmzSuIUJhjmGg$8HHYsj+88bSCxCGuj2RCk9rKKAVWID5CuKUy+mwLV1k=	2025-12-28 15:16:31.084891+00	f	Adrianenr	Adrian	Enrique	cesaradrianenr@gmail.com	f	t	2025-12-28 15:08:02.363709+00	cliente	33465768	2325594197	Av. Callao, 1442, CABA	1
66	pbkdf2_sha256$600000$EpESI8ebURFCFKOCSLmQAx$X+59Hs03En9MzHIOochcO4f7TmnG0f2mBiAsRo8ik2s=	2026-01-01 20:18:24.572912+00	f	silvana.zabala28	Silvana	Zabala	silvana.zabala28@gmail.com	f	t	2026-01-01 20:18:23.132454+00	cliente				1
65	pbkdf2_sha256$600000$tHSgH1QLlTaEUzWeHEkT4D$xQbMknF851gEnX4BOa6DC87FJNR5Mjzt67QEiVQdiv0=	2026-01-01 20:35:19.837371+00	f	laurireformed	lauri2	enrique	laurireformed@gmail.com	f	t	2026-01-01 19:58:36.632484+00	cliente				1
64	pbkdf2_sha256$600000$lkptLEAweCHamoZV58KWDO$j1QSU4OP9uhx7cLbLnQQYPe/2C7Lp11aFnEXmWWIFHM=	2026-01-01 20:38:07.734912+00	f	laureano54	Laureano	staff	laureano54@live.com.ar	f	t	2026-01-01 19:45:17+00	staff	\N	\N	\N	1
67	pbkdf2_sha256$600000$D54lOmiRwyrDXEzMJCjN32$CI6dTchX3QZQNxb/9kKjKVrXC4aJhKrmGOKbpZsdm6k=	2026-01-02 16:13:28.156708+00	f	mateodelutis	mateo	delutis	mateodelutis@gmail.com	f	t	2026-01-02 16:13:26.805688+00	cliente	43732882	02325472228		1
6	pbkdf2_sha256$600000$8pEpgy21ym3PzajyMuqRME$xB53C+NSanecNRCEbwcPnerFWPe4dGj8L08uOwRylTY=	2026-01-02 22:28:56.034392+00	t	admin			admin@gmail.com	t	t	2025-12-26 04:22:34.997721+00	cliente	\N	\N	\N	\N
\.


--
-- Data for Name: core_usuario_groups; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_usuario_groups (id, usuario_id, group_id) FROM stdin;
\.


--
-- Data for Name: core_usuario_user_permissions; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.core_usuario_user_permissions (id, usuario_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
8	2025-12-26 04:29:27.251661+00	2	Cancha Afuéra - Basanta	1	[{"added": {}}]	10	6
9	2025-12-26 04:29:46.275061+00	3	Cancha interior - Basanta	1	[{"added": {}}]	10	6
10	2025-12-26 04:30:02.042589+00	1	Interior	1	[{"added": {}}]	7	6
11	2025-12-26 04:30:05.072053+00	2	Exterior	1	[{"added": {}}]	7	6
12	2025-12-26 04:30:07.105182+00	3	Aire	1	[{"added": {}}]	7	6
13	2025-12-26 04:30:09.890612+00	4	Cemento	1	[{"added": {}}]	7	6
14	2025-12-26 04:30:12.738952+00	5	Sintetica	1	[{"added": {}}]	7	6
15	2025-12-26 04:30:16.216316+00	6	Blindex	1	[{"added": {}}]	7	6
16	2025-12-26 04:30:43.886714+00	2	Cancha Afuéra - Basanta	2	[{"changed": {"fields": ["Caracter\\u00edsticas"]}}]	10	6
17	2025-12-26 04:31:11.24362+00	1	Cancha Blindex - Basanta	2	[{"changed": {"fields": ["Duraci\\u00f3n del turno (minutos)", "Caracter\\u00edsticas"]}}]	10	6
18	2025-12-26 04:38:20.230002+00	1	Cliente1 (Cliente) - $600000.00 (Basanta)	1	[{"added": {}}]	15	6
19	2025-12-26 14:04:13.012369+00	2	juan perez (Cliente) - $600000.00 (Basanta)	1	[{"added": {}}]	15	6
20	2025-12-26 14:18:34.054713+00	11	pedro (Cliente)	3		6	6
21	2025-12-26 14:18:34.058448+00	9	recepciónista (Cliente)	3		6	6
22	2025-12-27 13:43:30.162243+00	22	Pedro rodriguez (Cliente) - $250000.00 (Basanta)	1	[{"added": {}}]	15	6
23	2025-12-27 17:31:28.297331+00	38	Nicolino Burgio (Staff)	3		6	6
24	2025-12-27 17:40:43.782416+00	29	asd (Cliente)	3		6	6
25	2025-12-27 17:40:43.789381+00	26	Carlos (Cliente)	3		6	6
26	2025-12-27 17:40:43.790761+00	35	Jose (Cliente)	3		6	6
27	2025-12-27 17:40:43.791984+00	12	Juan (Cliente)	3		6	6
28	2025-12-27 17:40:43.793138+00	28	juan (Cliente)	3		6	6
29	2025-12-27 17:40:43.794242+00	24	laurii (Cliente)	3		6	6
30	2025-12-27 17:40:43.795307+00	21	Pedro (Cliente)	3		6	6
31	2025-12-27 17:40:43.79622+00	22	Pedro (Cliente)	3		6	6
32	2025-12-27 17:40:43.797114+00	18	pedroo (Cliente)	3		6	6
33	2025-12-27 17:40:43.798215+00	25	Pedroooo (Cliente)	3		6	6
34	2025-12-27 17:40:43.799171+00	31	Santino (Cliente)	3		6	6
35	2025-12-27 17:40:43.800224+00	23	Silvana (Cliente)	3		6	6
36	2025-12-27 17:40:43.801415+00	20	viejita (Cliente)	3		6	6
37	2025-12-27 17:53:48.415096+00	40	Admin Dam (Staff)	2	[{"changed": {"fields": ["Last name", "Rol"]}}]	6	6
38	2025-12-27 21:20:23.662825+00	1	Padel Point	2	[{"changed": {"fields": ["Nombre", "Slug"]}}, {"changed": {"name": "Cancha", "object": "Cancha Afuera - Padel Point", "fields": ["Nombre"]}}]	8	6
39	2025-12-28 13:47:23.74009+00	1	Padel Point	2	[{"changed": {"fields": ["Direcci\\u00f3n", "Tel\\u00e9fono"]}}, {"changed": {"name": "Cancha", "object": "Blindex - Padel Point", "fields": ["Nombre", "Precio por hora"]}}, {"changed": {"name": "Cancha", "object": "Blindex 2 - Padel Point", "fields": ["Nombre", "Precio por hora"]}}, {"changed": {"name": "Cancha", "object": "Cancha interior - Padel Point", "fields": ["Activa"]}}]	8	6
40	2025-12-28 14:25:54.89387+00	1	Padel Point	2	[{"changed": {"fields": ["Instagram"]}}]	8	6
41	2026-01-01 19:44:34.646209+00	40	Admin Dam (Staff)	3		6	6
42	2026-01-01 19:44:34.651654+00	49	asdasd asdasd (Cliente)	3		6	6
43	2026-01-01 19:44:34.655708+00	7	Lauri Enrique (Cliente)	3		6	6
44	2026-01-01 19:44:34.659688+00	8	Juan Perez (Cliente)	3		6	6
45	2026-01-01 19:44:34.662614+00	57	a (Cliente)	3		6	6
46	2026-01-01 19:44:34.665635+00	61	Foden (Cliente)	3		6	6
47	2026-01-01 19:44:34.667886+00	62	Neymar (Cliente)	3		6	6
48	2026-01-01 19:44:34.670208+00	60	nico (Cliente)	3		6	6
49	2026-01-01 19:44:34.674676+00	53	Pedro (Cliente)	3		6	6
50	2026-01-01 19:44:34.73142+00	59	Pedro (Cliente)	3		6	6
51	2026-01-01 19:44:34.733958+00	63	thiago (Cliente)	3		6	6
52	2026-01-01 19:44:34.736626+00	44	vieja (Cliente)	3		6	6
53	2026-01-01 19:44:34.739287+00	37	Damaso Osamad (Cliente)	3		6	6
54	2026-01-01 19:44:34.741785+00	34	Jose Enrique (Cliente)	3		6	6
55	2026-01-01 19:44:34.744234+00	50	Juan Pavone (Cliente)	3		6	6
56	2026-01-01 19:44:34.746419+00	47	juan perez (Cliente)	3		6	6
57	2026-01-01 19:44:34.749344+00	33	Lauri vers (Cliente)	3		6	6
58	2026-01-01 19:44:34.752283+00	55	Laureano Enrique (Cliente)	3		6	6
59	2026-01-01 19:44:34.75464+00	56	Leo Usar (Cliente)	3		6	6
60	2026-01-01 19:44:34.756885+00	45	Leo Usar (Cliente)	3		6	6
61	2026-01-01 19:44:34.759174+00	46	Leo Usar (Cliente)	3		6	6
62	2026-01-01 19:44:34.761423+00	39	nu hy (Cliente)	3		6	6
63	2026-01-01 19:44:34.763672+00	32	Pedro rodriguez (Cliente)	3		6	6
64	2026-01-01 19:44:34.766918+00	10	recepcionista (Staff)	3		6	6
65	2026-01-01 19:45:41.945425+00	64	Laureano staff (Staff)	2	[{"changed": {"fields": ["Rol"]}}]	6	6
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	core	usuario
7	core	caracteristicacancha
8	core	complejo
9	core	preferenciascomplejo
10	core	cancha
11	core	administradorcomplejo
12	core	turnofijo
13	core	turno
14	core	bloqueo
15	core	creditocliente
16	core	integracionmercadopago
17	sites	site
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-12-25 16:13:55.00696+00
2	contenttypes	0002_remove_content_type_name	2025-12-25 16:13:55.015884+00
3	auth	0001_initial	2025-12-25 16:13:55.044771+00
4	auth	0002_alter_permission_name_max_length	2025-12-25 16:13:55.0479+00
5	auth	0003_alter_user_email_max_length	2025-12-25 16:13:55.050891+00
6	auth	0004_alter_user_username_opts	2025-12-25 16:13:55.054019+00
7	auth	0005_alter_user_last_login_null	2025-12-25 16:13:55.057198+00
8	auth	0006_require_contenttypes_0002	2025-12-25 16:13:55.058454+00
9	auth	0007_alter_validators_add_error_messages	2025-12-25 16:13:55.061758+00
10	auth	0008_alter_user_username_max_length	2025-12-25 16:13:55.065897+00
11	auth	0009_alter_user_last_name_max_length	2025-12-25 16:13:55.069341+00
12	auth	0010_alter_group_name_max_length	2025-12-25 16:13:55.073079+00
13	auth	0011_update_proxy_permissions	2025-12-25 16:13:55.076297+00
14	auth	0012_alter_user_first_name_max_length	2025-12-25 16:13:55.079606+00
15	core	0001_initial	2025-12-25 16:13:55.181677+00
16	admin	0001_initial	2025-12-25 16:13:55.195905+00
17	admin	0002_logentry_remove_auto_add	2025-12-25 16:13:55.202977+00
18	admin	0003_logentry_add_action_flag_choices	2025-12-25 16:13:55.208946+00
19	sessions	0001_initial	2025-12-25 16:13:55.216334+00
20	core	0002_bloqueo_creditocliente_integracionmercadopago_and_more	2025-12-25 17:01:09.847143+00
21	core	0003_add_bloqueado_estado	2025-12-27 04:07:04.896796+00
22	core	0004_add_performance_indexes	2025-12-27 04:26:23.267816+00
23	core	0005_add_subdominio_field	2025-12-28 13:51:37.825124+00
24	core	0006_complejo_direccion_detallada_complejo_instagram_and_more	2025-12-28 14:24:57.182715+00
25	core	0007_turno_unique_active_constraint	2025-12-28 17:30:41.248947+00
26	core	0007_add_auditoria_creditos	2025-12-30 01:21:35.626397+00
27	core	0008_merge_0007_migrations	2025-12-30 01:21:35.638571+00
28	core	0009_add_jugado_estado	2025-12-30 01:21:35.783243+00
29	sites	0001_initial	2026-01-01 20:20:19.605322+00
30	sites	0002_alter_domain_unique	2026-01-01 20:20:19.618893+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
fyaa7zbey8yrljzkuehtu2b54m8x0hy7	.eJxVjEEOwiAQRe_C2hBgOjC4dO8ZyHQAWzVtUtqV8e7apAvd_vfef6nE2zqkrZUljVmdFXTq9Dv2LI8y7STfebrNWuZpXcZe74o-aNPXOZfn5XD_DgZuw7cuBtBaCC57HyP7gEw2GqLMYDpD2aOAA_IuRJQasaNQfbVIKFacqPcHxG42dA:1vZY07:IBIIZ09rDnk2v_pkpUoPuLY-IZGl-UdfPNz-Wh8hBWY	2026-01-10 17:22:47.04045+00
x6p74kz2uyl2pp8bdtvuwvmp9lcvr63b	.eJxVjDsOwjAQBe_iGllex79Q0nMGa71r4wBypDipEHeHSCmgfTPzXiLitta49bzEicVZgBKn3zEhPXLbCd-x3WZJc1uXKcldkQft8jpzfl4O9--gYq_furBlGkuAYIJTkH0pSGQ8KEOEAyBqZxlYWQ1eh4TGDkENihyEUsYk3h8Rwzf0:1vZSm5:LafoLD6Fwo2cLOpEgN_m6RCOH7dIJVXFbGnuCsygtoM	2026-01-10 11:47:57.553844+00
a6vl1dsdpbl56n97vkprpe1txd5cvm7o	.eJxVjDsOwyAQBe9CHSEwaz4p0_sMaIElOIlAMnYV5e6xJRdJ-2bmvZnHbS1-67T4ObErU45dfseA8Un1IOmB9d54bHVd5sAPhZ-086klet1O9--gYC97jSGANhKFtjYPgmRU4AapXMggEMYsgRSSsTmPzmSzW6CFTjaSJRMj-3wBAPk4Jg:1vZY86:vrdSRFh2vv17YOr3J3-luRrGE7QMTNUTd-5obeMK6Lw	2026-01-10 17:31:02.279076+00
3v34zuk19te5gdfmtk0hbdnfp6bs1rm7	.eJxVjMsOwiAQRf-FtSHDs-DSvd9AmAGkaiAp7cr479qkC93ec859sRC3tYZt5CXMiZ2ZBnb6HTHSI7edpHtst86pt3WZke8KP-jg157y83K4fwc1jvqtpdLFgAAPFqLx0sHkRAFKqCSRTOiFI1IFUCNaa1EbKpMnKEkLJYi9P-PBN7k:1vZYSm:6PlpLXTMcXbTF3tGLrNu23LXh48idFYUCH7FozcHwEw	2026-01-10 17:52:24.809674+00
wpiy2drjvtopvv8qrlrxbsg09pm3ykd4	.eJxVjEsOAiEQBe_C2pBGfuLSvWcgDd3IqIFkmFkZ766TzEK3r6reS0RclxrXwXOcSJyFF4ffLWF-cNsA3bHdusy9LfOU5KbInQ557cTPy-7-HVQc9Vsn44ggeNIKjQnFsgsAHiFbLlYpIJfc0QA462zQOTFiIZW5nEDbUMT7A9mCN9A:1vYzsx:uMBxgDEHWn2HHEMVTIYBS41g6fscgzfaBbLYThh3SQA	2026-01-09 04:57:07.078776+00
hew1gvc1tac9ouyrjwiaucpgb1w25x6u	.eJxVjDsOwjAQBe_iGllex79Q0nMGa71r4wBypDipEHeHSCmgfTPzXiLitta49bzEicVZgBKn3zEhPXLbCd-x3WZJc1uXKcldkQft8jpzfl4O9--gYq_furBlGkuAYIJTkH0pSGQ8KEOEAyBqZxlYWQ1eh4TGDkENihyEUsYk3h8Rwzf0:1vZYis:ptmVY0cc0df2uih4EOTnrPMa-L-Of40kTZyTQSHYJ5Q	2026-01-10 18:09:02.272336+00
igp4uslubob56vtahr72d9mjabsr33pq	.eJxVjDsOwjAQBe_iGllex79Q0nMGa71r4wBypDipEHeHSCmgfTPzXiLitta49bzEicVZgBKn3zEhPXLbCd-x3WZJc1uXKcldkQft8jpzfl4O9--gYq_furBlGkuAYIJTkH0pSGQ8KEOEAyBqZxlYWQ1eh4TGDkENihyEUsYk3h8Rwzf0:1vZV7a:Myd5RWVxMcgX3q1tmFR2bMpb0ofHtJukFusQ5PdT8i8	2026-01-10 14:18:18.821096+00
lgszkv1reqsrhe6ninwk3isv9lyok3w4	.eJxVjMEOwiAQRP-FsyEUWAGP3v0GsruAVA1NSnsy_rtt0oPOcd6beYuI61Lj2vMcxyQuwonTb0fIz9x2kB7Y7pPkqS3zSHJX5EG7vE0pv66H-3dQsddtTYP2RisCSpCZB-cdlGATWPCBMIFiZYq1ZosNcC7FWGRTtAJGUiQ-X9URN5c:1vZs8B:bBxj9jsZu41WytWta8AtKn9aA3hMM7AWHcJgMHX1tew	2026-01-11 14:52:27.386401+00
52p5wcpf0ohgs1ju1fw8tmrvuro63f8o	.eJxVjDsOwyAQRO9CHSHAfFOm9xkQy66DkwgkY1dR7h5bcpE0U8x7M28W07aWuHVa4ozsyrRkl98SUn5SPQg-Ur03nltdlxn4ofCTdj42pNftdP8OSuplX7ugNaAwQifYAwkdIgU1-WnI2ZInUIYsDM4Z74ZAYCQGRWSkssoI9vkCF7A4Fw:1vZaHj:P3FPXs0X0ElBb1OW9cYHzhndycD7g1gatB00L43dVLc	2026-01-10 19:49:07.287421+00
ws5pj0xcmini9qcbcgqxrsrb5j90qpfy	.eJxVjDsOwjAQBe_iGlnxev2jpM8ZrLXX4ABypDipEHeHSCmgfTPzXiLStta49bLEicVZqEGcfsdE-VHaTvhO7TbLPLd1mZLcFXnQLseZy_NyuH8HlXr91kErMJiYibUlVIXJ56D9dfCgnXU2UFIFQGEyNoWM6AAVgGc0DgyI9wf0DDbe:1vZbDo:XawcC4Lj66zypae9P9BEpEj2O_ubP661kXFRo9SzWwU	2026-01-10 20:49:08.851278+00
j77919jld864ehd9aru65476rmk4ji1q	.eJxVjEEOwiAQRe_C2hDIFBhcuvcMZIBBqgaS0q6Md9cmXej2v_f-SwTa1hq2wUuYszgLK06_W6T04LaDfKd26zL1ti5zlLsiDzrktWd-Xg7376DSqN9a6QjZ0cTWKwbUpbByGZIhRgeaLXnkFCdbqGDxQAbQYybjEJnAifcH9fI4WA:1vZbR2:VqusbMFeOh00kY2jIIVSu_TC3LDLnKHmUdoaWNQcMEw	2026-01-10 21:02:48.761015+00
ba7h37p2klfhv0gljdit7zamxvlqvuhh	.eJxVjMEOwiAQRP-FsyEUWAGP3v0GsruAVA1NSnsy_rtt0oPOcd6beYuI61Lj2vMcxyQuwonTb0fIz9x2kB7Y7pPkqS3zSHJX5EG7vE0pv66H-3dQsddtTYP2RisCSpCZB-cdlGATWPCBMIFiZYq1ZosNcC7FWGRTtAJGUiQ-X9URN5c:1vZbRL:883N7F6EqHXtXKbzup1tlwBihyha2wf5BL7TkkTqv8k	2026-01-10 21:03:07.863163+00
jqqc55rybuwnahasltsiuguxby2g4qtz	.eJxVjEEOwiAQRe_C2hDIFBhcuvcMZIBBqgaS0q6Md9cmXej2v_f-SwTa1hq2wUuYszgLK06_W6T04LaDfKd26zL1ti5zlLsiDzrktWd-Xg7376DSqN9a6QjZ0cTWKwbUpbByGZIhRgeaLXnkFCdbqGDxQAbQYybjEJnAifcH9fI4WA:1vZbVZ:H0R7Qemzo-7FhlAlZl-bALB4MxrSjvPn8txJdhAQObk	2026-01-10 21:07:29.542178+00
vftetw03v2i04ch8pvmkk44f3ctw7etv	.eJxVjDsOwyAQRO9CHSHAyy9lep_BYtlVcBKBZOwqyt1jSy6SKee9mbeY0raWaeu8TDOJqwAjLr8lpvzkehB6pHpvMre6LjPKQ5En7XJsxK_b6f4dlNTLvtYMOUawFohN9AEYHUVyTumszEDBkCOO3sKQlPaZEfYExUBo0LH4fAHztTez:1vZdpp:mXXeVfpmiElwma4l3U1E84hhqX5lqvxdkVjB43yqlx4	2026-01-10 23:36:33.154572+00
e4prxzbqjdhwnkyooz49aflzno2uek24	.eJxVjEEOwiAQRe_C2hBKKYMu3XsGMswMUjU0Ke3KeHfbpAvd_vfef6uI61Li2mSOI6uLcr06_Y4J6Sl1J_zAep80TXWZx6R3RR-06dvE8roe7t9BwVa2mjgjM3knYq1PGQg8Ag3dIPmcIJAzZNgYx7BJFpzvc8idMCbKLEF9vkPYOY8:1vZe3V:OdXWfAi8aeYnBSM2tc0vXlK_YgTkGF6Jh0BlWFwTcJs	2026-01-10 23:50:41.759862+00
5qmo84jmrxjcgtsvtjalyfc8h5edrhcm	.eJxVjMEKwyAQRP_Fc5FI1mh67L3fIKu7W9MWhZicQv-9CeTQwpzmvZlNBVyXHNbGc5hIXRVYdfktI6YXl4PQE8uj6lTLMk9RH4o-adP3Svy-ne7fQcaW9zUaIUqCexBiL8l4IT96AI49uth5z4N1o0t-IAsWuHMJiKwBca4T9fkCUMo5EQ:1vZeQW:5H-65_N9552SIZDPXn2utZVQ0EqS4xpHJ-W5AFONFA4	2026-01-11 00:14:28.863588+00
w7v2hxl5d3g98ykz7ad4d5dffcfj7jua	.eJxVjEEOwiAQRe_C2pABgRaX7nsGMsMMUjVtUtqV8e7apAvd_vfef6mE21rT1mRJI6uLckGdfkfC_JBpJ3zH6TbrPE_rMpLeFX3QpoeZ5Xk93L-Diq1-a89RzmAjQ-bsLcQOPATuC7iCPRTCQEgEHBGMRUdCnZVSjDjvrDPq_QEUWjh5:1vZeR5:JR4TYhzCoqSgQ3mGp3mRGW-q-52JsFO6MAgSeQ-VApo	2026-01-11 00:15:03.442286+00
sqc0jfvjns9r4217gvoof1o1p0nd7ps0	.eJxVjEEOwiAQRe_C2hDIFBhcuvcMZIBBqgaS0q6Md9cmXej2v_f-SwTa1hq2wUuYszgLK06_W6T04LaDfKd26zL1ti5zlLsiDzrktWd-Xg7376DSqN9a6QjZ0cTWKwbUpbByGZIhRgeaLXnkFCdbqGDxQAbQYybjEJnAifcH9fI4WA:1vZeTF:-nCL_9UwuIGPZGa71ZEhHWDRmb0J6LJMATO5ogZmjGo	2026-01-11 00:17:17.552587+00
qddvsrukak7q2cgrbto7iom58fpldmgt	.eJxVjMEKwyAQRP_Fc5FI1mh67L3fIKu7W9MWhZicQv-9CeTQwpzmvZlNBVyXHNbGc5hIXRVYdfktI6YXl4PQE8uj6lTLMk9RH4o-adP3Svy-ne7fQcaW9zUaIUqCexBiL8l4IT96AI49uth5z4N1o0t-IAsWuHMJiKwBca4T9fkCUMo5EQ:1vZeUy:t5iCHUyIOl3qm2oj10kWrzoF-fmhDj8EmRS1_h-lfx0	2026-01-11 00:19:04.365123+00
ve2dojutwmjfd9gs4gpxm0pokn4nj4gy	.eJxVjMsOwiAQRf-FtSE8Bsi4dO83EBgGqRqalHZl_Hdt0oVu7znnvkRM29riNniJUxFnAUGcfsec6MF9J-We-m2WNPd1mbLcFXnQIa9z4eflcP8OWhrtW5Ny2oLyAREtExUMFqBmQucIbQF0GhSbmnPQXCEUJo3WZ5XYm2DE-wP0Kje7:1vZqcn:75yEpO6NiRRbP-PtpTmEd6N8WA2EIyzp-l7-wt0Ry9c	2026-01-11 13:15:57.430478+00
jyq757gmu94n7hu7zr2mniczfkkbqyno	.eJxVjMsOwiAQRf-FtSHyBpfu-w1khgGpGkhKuzL-uzbpQrf3nHNfLMK21riNvMSZ2IXpwE6_I0J65LYTukO7dZ56W5cZ-a7wgw4-dcrP6-H-HVQY9VtLLV2hAMUBeaJgIRvUktAiKgClQiGfzsI4GZxBIqeUtzp7J4SRRrP3By09OBw:1vZqdI:oc4roj54NIk3Kmpu2sVCOqEMv44ggetiBxOVzEqmtbY	2026-01-11 13:16:28.45151+00
906q5q8th7gwxqoeuu26z3n6fn4w520m	.eJxVjMEOwiAQRP-FsyEUWAgevfsNhGUXqRqalPbU-O-2SQ96m8x7M5uIaV1qXDvPcSRxFaDE5bfElF_cDkLP1B6TzFNb5hHlociTdnmfiN-30_07qKnXfe1zYHRFO0swKMvFWiYPhowDDyFY7QYTrMqJkRADaCCdjOJistuT-HwB_jw4CQ:1vZrO0:r1Kp3zgM7v6k03NvX-kddBeE-v49l09ygQOkkLVsRF8	2026-01-11 14:04:44.55103+00
xoqgpf29ov4zy5o015t3e8yj7lpk4tm3	.eJxVjMsOwiAQRf-FtSE8Rh4u3fsNZGBAqgaS0q6M_26bdKHbe865bxZwXWpYR57DROzCzo6dfseI6ZnbTuiB7d556m2Zp8h3hR908Fun_Loe7t9BxVG3OoJU4BB8sQqzcDJagFQQBXpfnNZgi86GhFdGOh03Rk5p8LKURGTY5wsB3DgY:1vabUU:hrCLv28z_smBDZoAJag60Bn2d6CEQzz9uzPk2TyOTtI	2026-01-13 15:18:30.032899+00
8vdnytc7nzibpt5zlhzd82fgon0dk3ci	.eJxVjMEOwiAQRP-FsyEUWAgevfsNhGUXqRqalPbU-O-2SQ96m8x7M5uIaV1qXDvPcSRxFaDE5bfElF_cDkLP1B6TzFNb5hHlociTdnmfiN-30_07qKnXfe1zYHRFO0swKMvFWiYPhowDDyFY7QYTrMqJkRADaCCdjOJistuT-HwB_jw4CQ:1vZrpD:aTLOBqYbsGug7xUuxJJM1c6VLlLpNOYpAyOs4JMsWwY	2026-01-11 14:32:51.275949+00
t38mlik0yfsknjmh0sl14kvpcd7sl0m6	.eJxVjMEOwiAQRP-FsyEUWAgevfsNhGUXqRqalPbU-O-2SQ96m8x7M5uIaV1qXDvPcSRxFaDE5bfElF_cDkLP1B6TzFNb5hHlociTdnmfiN-30_07qKnXfe1zYHRFO0swKMvFWiYPhowDDyFY7QYTrMqJkRADaCCdjOJistuT-HwB_jw4CQ:1vZrpE:Hwl3KjZ7ok1OQ04IoXVmKS66dtJ1lgXdFHVkIg3m0uY	2026-01-11 14:32:52.789635+00
gawyn7shmfkyry4z5r98it17pkd9lzxf	.eJxVjEEOwiAQRe_C2hDIFBhcuvcMZIBBqgaS0q6Md9cmXej2v_f-SwTa1hq2wUuYszgLK06_W6T04LaDfKd26zL1ti5zlLsiDzrktWd-Xg7376DSqN9a6QjZ0cTWKwbUpbByGZIhRgeaLXnkFCdbqGDxQAbQYybjEJnAifcH9fI4WA:1vbeXe:WNc51CX4-iPsj_p8n_1HurQmG_AbvwTrBNU1QyS3K28	2026-01-16 12:46:06.84194+00
e203eqzlss0tq71qzb4m0ydjxjyld79o	.eJxVjDsOwjAQBe_iGllrZ-MPJT1niNbeDQ4gR4qTCnF3iJQC2jcz76UG2tYybE2WYWJ1Vs6r0--YKD-k7oTvVG-zznNdlynpXdEHbfo6szwvh_t3UKiVb-2dGVNmFGtil0ECGnDOi4-xB8QQhaGjznuk4NBYBkM0MtoRcjI9qfcH7qc3cw:1vbhmK:BI34fQtfYbrYEwrjSkfPYILQgEU608vSkQiQGzXTxzs	2026-01-16 16:13:28.16019+00
ilnt0hbkfapota128r9zl36gd9srl4gq	.eJxVjEEOwiAQRe_C2hDIFBhcuvcMZIBBqgaS0q6Md9cmXej2v_f-SwTa1hq2wUuYszgLK06_W6T04LaDfKd26zL1ti5zlLsiDzrktWd-Xg7376DSqN9a6QjZ0cTWKwbUpbByGZIhRgeaLXnkFCdbqGDxQAbQYybjEJnAifcH9fI4WA:1vbiIh:jcVXqrapJ4xTSJF7SzqRA6UNVEuZptNEACrP0usmXjo	2026-01-16 16:46:55.344451+00
i689qd7raklcclr2noi72v0lo16mladr	.eJxVjDsOwyAQBe9CHSHzMeCU6X0GtOwuwUmEJWNXUe4eIblI2jcz7y0iHHuJR-MtLiSuYnTi8jsmwCfXTugB9b5KXOu-LUl2RZ60yXklft1O9--gQCu91t4FDgYdw0CBlCPtPKFVmcmMSvvBIXkzKdLAKUHOEwUEo3T2aK34fAEctjjN:1vaNhj:m6lQuU46ZkyB-KIc4Ax5YW3kruGWYU6eInUZoG61ODs	2026-01-13 00:35:15.811403+00
v8wr3rgu639k5908jmdad2qpjie3ooex	.eJxVjEEOwiAQRe_C2hDIFBhcuvcMZIBBqgaS0q6Md9cmXej2v_f-SwTa1hq2wUuYszgLK06_W6T04LaDfKd26zL1ti5zlLsiDzrktWd-Xg7376DSqN9a6QjZ0cTWKwbUpbByGZIhRgeaLXnkFCdbqGDxQAbQYybjEJnAifcH9fI4WA:1vbndg:iwpKQKuWowy9KhZ5sbN5nowcee_8bz96aiZlCkTw8Ss	2026-01-16 22:28:56.039291+00
6xcd564cth5khew5bn5vkufho13tww1u	.eJxVjsEOwiAQRP-FsyEtXZbq0Xu_gSzsKlUDSWlPxn-XJj3odd6bybyVp21Nfquy-JnVRSGo028YKD4l74QflO9Fx5LXZQ56V_RBq54Ky-t6uH8DiWpqbTKRADpCg46NiIQbIFggAW7h2fURYXARxq6PwQQSBHKDHS0OzO3V5wsT6jf_:1vbPQt:ddIjdv8To92hEvrKQIiMZPmejBK38NiQiZjXLcd3jb8	2026-01-15 20:38:07.73835+00
\.


--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: lauri11
--

COPY public.django_site (id, domain, name) FROM stdin;
1	example.com	example.com
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: core_bloqueo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_bloqueo_id_seq', 5, true);


--
-- Name: core_cancha_caracteristicas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_cancha_caracteristicas_id_seq', 4, true);


--
-- Name: core_cancha_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_cancha_id_seq', 3, true);


--
-- Name: core_caracteristicacancha_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_caracteristicacancha_id_seq', 6, true);


--
-- Name: core_complejo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_complejo_id_seq', 1, true);


--
-- Name: core_creditocliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_creditocliente_id_seq', 80, true);


--
-- Name: core_integracionmercadopago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_integracionmercadopago_id_seq', 1, false);


--
-- Name: core_preferenciascomplejo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_preferenciascomplejo_id_seq', 1, true);


--
-- Name: core_turno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_turno_id_seq', 114, true);


--
-- Name: core_turnofijo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_turnofijo_id_seq', 11, true);


--
-- Name: core_usuario_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_usuario_groups_id_seq', 1, false);


--
-- Name: core_usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_usuario_id_seq', 67, true);


--
-- Name: core_usuario_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.core_usuario_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 65, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lauri11
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: core_bloqueo core_bloqueo_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_bloqueo
    ADD CONSTRAINT core_bloqueo_pkey PRIMARY KEY (id);


--
-- Name: core_cancha_caracteristicas core_cancha_caracteristi_cancha_id_caracteristica_3394dc12_uniq; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_cancha_caracteristicas
    ADD CONSTRAINT core_cancha_caracteristi_cancha_id_caracteristica_3394dc12_uniq UNIQUE (cancha_id, caracteristicacancha_id);


--
-- Name: core_cancha_caracteristicas core_cancha_caracteristicas_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_cancha_caracteristicas
    ADD CONSTRAINT core_cancha_caracteristicas_pkey PRIMARY KEY (id);


--
-- Name: core_cancha core_cancha_complejo_id_nombre_0e68f52f_uniq; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_cancha
    ADD CONSTRAINT core_cancha_complejo_id_nombre_0e68f52f_uniq UNIQUE (complejo_id, nombre);


--
-- Name: core_cancha core_cancha_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_cancha
    ADD CONSTRAINT core_cancha_pkey PRIMARY KEY (id);


--
-- Name: core_caracteristicacancha core_caracteristicacancha_nombre_key; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_caracteristicacancha
    ADD CONSTRAINT core_caracteristicacancha_nombre_key UNIQUE (nombre);


--
-- Name: core_caracteristicacancha core_caracteristicacancha_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_caracteristicacancha
    ADD CONSTRAINT core_caracteristicacancha_pkey PRIMARY KEY (id);


--
-- Name: core_complejo core_complejo_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_complejo
    ADD CONSTRAINT core_complejo_pkey PRIMARY KEY (id);


--
-- Name: core_complejo core_complejo_slug_key; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_complejo
    ADD CONSTRAINT core_complejo_slug_key UNIQUE (slug);


--
-- Name: core_complejo core_complejo_subdominio_key; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_complejo
    ADD CONSTRAINT core_complejo_subdominio_key UNIQUE (subdominio);


--
-- Name: core_creditocliente core_creditocliente_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_creditocliente
    ADD CONSTRAINT core_creditocliente_pkey PRIMARY KEY (id);


--
-- Name: core_integracionmercadopago core_integracionmercadopago_complejo_id_key; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_integracionmercadopago
    ADD CONSTRAINT core_integracionmercadopago_complejo_id_key UNIQUE (complejo_id);


--
-- Name: core_integracionmercadopago core_integracionmercadopago_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_integracionmercadopago
    ADD CONSTRAINT core_integracionmercadopago_pkey PRIMARY KEY (id);


--
-- Name: core_preferenciascomplejo core_preferenciascomplejo_complejo_id_key; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_preferenciascomplejo
    ADD CONSTRAINT core_preferenciascomplejo_complejo_id_key UNIQUE (complejo_id);


--
-- Name: core_preferenciascomplejo core_preferenciascomplejo_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_preferenciascomplejo
    ADD CONSTRAINT core_preferenciascomplejo_pkey PRIMARY KEY (id);


--
-- Name: core_turno core_turno_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_turno
    ADD CONSTRAINT core_turno_pkey PRIMARY KEY (id);


--
-- Name: core_turnofijo core_turnofijo_cancha_id_dia_semana_hora_inicio_d57e4dbf_uniq; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_turnofijo
    ADD CONSTRAINT core_turnofijo_cancha_id_dia_semana_hora_inicio_d57e4dbf_uniq UNIQUE (cancha_id, dia_semana, hora_inicio);


--
-- Name: core_turnofijo core_turnofijo_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_turnofijo
    ADD CONSTRAINT core_turnofijo_pkey PRIMARY KEY (id);


--
-- Name: core_usuario_groups core_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario_groups
    ADD CONSTRAINT core_usuario_groups_pkey PRIMARY KEY (id);


--
-- Name: core_usuario_groups core_usuario_groups_usuario_id_group_id_bde3c750_uniq; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario_groups
    ADD CONSTRAINT core_usuario_groups_usuario_id_group_id_bde3c750_uniq UNIQUE (usuario_id, group_id);


--
-- Name: core_usuario core_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario
    ADD CONSTRAINT core_usuario_pkey PRIMARY KEY (id);


--
-- Name: core_usuario_user_permissions core_usuario_user_permis_usuario_id_permission_id_7a048d24_uniq; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario_user_permissions
    ADD CONSTRAINT core_usuario_user_permis_usuario_id_permission_id_7a048d24_uniq UNIQUE (usuario_id, permission_id);


--
-- Name: core_usuario_user_permissions core_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario_user_permissions
    ADD CONSTRAINT core_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: core_usuario core_usuario_username_key; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario
    ADD CONSTRAINT core_usuario_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: bloqueo_complejo_fecha_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX bloqueo_complejo_fecha_idx ON public.core_bloqueo USING btree (complejo_id, fecha);


--
-- Name: bloqueo_fecha_cancha_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX bloqueo_fecha_cancha_idx ON public.core_bloqueo USING btree (fecha, cancha_id);


--
-- Name: core_bloqueo_cancha_id_33cadfc7; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_bloqueo_cancha_id_33cadfc7 ON public.core_bloqueo USING btree (cancha_id);


--
-- Name: core_bloqueo_complejo_id_98d281f8; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_bloqueo_complejo_id_98d281f8 ON public.core_bloqueo USING btree (complejo_id);


--
-- Name: core_bloqueo_created_by_id_f59fa657; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_bloqueo_created_by_id_f59fa657 ON public.core_bloqueo USING btree (created_by_id);


--
-- Name: core_cancha_caracteristicas_cancha_id_fac22f92; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_cancha_caracteristicas_cancha_id_fac22f92 ON public.core_cancha_caracteristicas USING btree (cancha_id);


--
-- Name: core_cancha_caracteristicas_caracteristicacancha_id_dd7d789f; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_cancha_caracteristicas_caracteristicacancha_id_dd7d789f ON public.core_cancha_caracteristicas USING btree (caracteristicacancha_id);


--
-- Name: core_cancha_complejo_id_89681f40; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_cancha_complejo_id_89681f40 ON public.core_cancha USING btree (complejo_id);


--
-- Name: core_caracteristicacancha_nombre_f17c0061_like; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_caracteristicacancha_nombre_f17c0061_like ON public.core_caracteristicacancha USING btree (nombre varchar_pattern_ops);


--
-- Name: core_complejo_slug_5d4419c7_like; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_complejo_slug_5d4419c7_like ON public.core_complejo USING btree (slug varchar_pattern_ops);


--
-- Name: core_complejo_subdominio_7e653b3a_like; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_complejo_subdominio_7e653b3a_like ON public.core_complejo USING btree (subdominio varchar_pattern_ops);


--
-- Name: core_creditocliente_complejo_id_9c06e531; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_creditocliente_complejo_id_9c06e531 ON public.core_creditocliente USING btree (complejo_id);


--
-- Name: core_creditocliente_creado_por_id_4547c4b3; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_creditocliente_creado_por_id_4547c4b3 ON public.core_creditocliente USING btree (creado_por_id);


--
-- Name: core_creditocliente_modificado_por_id_678a1ed8; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_creditocliente_modificado_por_id_678a1ed8 ON public.core_creditocliente USING btree (modificado_por_id);


--
-- Name: core_creditocliente_turno_origen_id_024a2c4b; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_creditocliente_turno_origen_id_024a2c4b ON public.core_creditocliente USING btree (turno_origen_id);


--
-- Name: core_creditocliente_usuario_id_be538a88; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_creditocliente_usuario_id_be538a88 ON public.core_creditocliente USING btree (usuario_id);


--
-- Name: core_turno_cancha_id_209f6e0c; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_turno_cancha_id_209f6e0c ON public.core_turno USING btree (cancha_id);


--
-- Name: core_turno_cliente_id_fd853b13; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_turno_cliente_id_fd853b13 ON public.core_turno USING btree (cliente_id);


--
-- Name: core_turnofijo_cancha_id_c67e16d2; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_turnofijo_cancha_id_c67e16d2 ON public.core_turnofijo USING btree (cancha_id);


--
-- Name: core_turnofijo_cliente_id_00c96fe7; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_turnofijo_cliente_id_00c96fe7 ON public.core_turnofijo USING btree (cliente_id);


--
-- Name: core_usuario_complejo_id_4e2fd699; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_usuario_complejo_id_4e2fd699 ON public.core_usuario USING btree (complejo_id);


--
-- Name: core_usuario_groups_group_id_55312a9a; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_usuario_groups_group_id_55312a9a ON public.core_usuario_groups USING btree (group_id);


--
-- Name: core_usuario_groups_usuario_id_97385234; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_usuario_groups_usuario_id_97385234 ON public.core_usuario_groups USING btree (usuario_id);


--
-- Name: core_usuario_user_permissions_permission_id_7f881653; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_usuario_user_permissions_permission_id_7f881653 ON public.core_usuario_user_permissions USING btree (permission_id);


--
-- Name: core_usuario_user_permissions_usuario_id_ce4108a7; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_usuario_user_permissions_usuario_id_ce4108a7 ON public.core_usuario_user_permissions USING btree (usuario_id);


--
-- Name: core_usuario_username_87fc6a94_like; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX core_usuario_username_87fc6a94_like ON public.core_usuario USING btree (username varchar_pattern_ops);


--
-- Name: credito_activo_created_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX credito_activo_created_idx ON public.core_creditocliente USING btree (activo, created_at);


--
-- Name: credito_usuario_complejo_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX credito_usuario_complejo_idx ON public.core_creditocliente USING btree (usuario_id, complejo_id, activo);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: turno_cancha_fecha_hora_unico_activo; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE UNIQUE INDEX turno_cancha_fecha_hora_unico_activo ON public.core_turno USING btree (cancha_id, fecha, hora_inicio) WHERE (NOT ((estado)::text = ANY ((ARRAY['cancelado_usuario'::character varying, 'cancelado_admin'::character varying, 'expirado'::character varying])::text[])));


--
-- Name: turno_cancha_fecha_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX turno_cancha_fecha_idx ON public.core_turno USING btree (cancha_id, fecha);


--
-- Name: turno_cliente_estado_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX turno_cliente_estado_idx ON public.core_turno USING btree (cliente_id, estado);


--
-- Name: turno_estado_created_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX turno_estado_created_idx ON public.core_turno USING btree (estado, created_at);


--
-- Name: turno_fecha_estado_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX turno_fecha_estado_idx ON public.core_turno USING btree (fecha, estado);


--
-- Name: turno_fecha_hora_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX turno_fecha_hora_idx ON public.core_turno USING btree (fecha, hora_inicio);


--
-- Name: turnofijo_activo_dia_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX turnofijo_activo_dia_idx ON public.core_turnofijo USING btree (activo, dia_semana);


--
-- Name: turnofijo_cancha_activo_idx; Type: INDEX; Schema: public; Owner: lauri11
--

CREATE INDEX turnofijo_cancha_activo_idx ON public.core_turnofijo USING btree (cancha_id, activo);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_bloqueo core_bloqueo_cancha_id_33cadfc7_fk_core_cancha_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_bloqueo
    ADD CONSTRAINT core_bloqueo_cancha_id_33cadfc7_fk_core_cancha_id FOREIGN KEY (cancha_id) REFERENCES public.core_cancha(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_bloqueo core_bloqueo_complejo_id_98d281f8_fk_core_complejo_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_bloqueo
    ADD CONSTRAINT core_bloqueo_complejo_id_98d281f8_fk_core_complejo_id FOREIGN KEY (complejo_id) REFERENCES public.core_complejo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_bloqueo core_bloqueo_created_by_id_f59fa657_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_bloqueo
    ADD CONSTRAINT core_bloqueo_created_by_id_f59fa657_fk_core_usuario_id FOREIGN KEY (created_by_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cancha_caracteristicas core_cancha_caracter_cancha_id_fac22f92_fk_core_canc; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_cancha_caracteristicas
    ADD CONSTRAINT core_cancha_caracter_cancha_id_fac22f92_fk_core_canc FOREIGN KEY (cancha_id) REFERENCES public.core_cancha(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cancha_caracteristicas core_cancha_caracter_caracteristicacancha_dd7d789f_fk_core_cara; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_cancha_caracteristicas
    ADD CONSTRAINT core_cancha_caracter_caracteristicacancha_dd7d789f_fk_core_cara FOREIGN KEY (caracteristicacancha_id) REFERENCES public.core_caracteristicacancha(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cancha core_cancha_complejo_id_89681f40_fk_core_complejo_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_cancha
    ADD CONSTRAINT core_cancha_complejo_id_89681f40_fk_core_complejo_id FOREIGN KEY (complejo_id) REFERENCES public.core_complejo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_creditocliente core_creditocliente_complejo_id_9c06e531_fk_core_complejo_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_creditocliente
    ADD CONSTRAINT core_creditocliente_complejo_id_9c06e531_fk_core_complejo_id FOREIGN KEY (complejo_id) REFERENCES public.core_complejo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_creditocliente core_creditocliente_creado_por_id_4547c4b3_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_creditocliente
    ADD CONSTRAINT core_creditocliente_creado_por_id_4547c4b3_fk_core_usuario_id FOREIGN KEY (creado_por_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_creditocliente core_creditocliente_modificado_por_id_678a1ed8_fk_core_usua; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_creditocliente
    ADD CONSTRAINT core_creditocliente_modificado_por_id_678a1ed8_fk_core_usua FOREIGN KEY (modificado_por_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_creditocliente core_creditocliente_turno_origen_id_024a2c4b_fk_core_turno_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_creditocliente
    ADD CONSTRAINT core_creditocliente_turno_origen_id_024a2c4b_fk_core_turno_id FOREIGN KEY (turno_origen_id) REFERENCES public.core_turno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_creditocliente core_creditocliente_usuario_id_be538a88_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_creditocliente
    ADD CONSTRAINT core_creditocliente_usuario_id_be538a88_fk_core_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_integracionmercadopago core_integracionmerc_complejo_id_e14e7705_fk_core_comp; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_integracionmercadopago
    ADD CONSTRAINT core_integracionmerc_complejo_id_e14e7705_fk_core_comp FOREIGN KEY (complejo_id) REFERENCES public.core_complejo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_preferenciascomplejo core_preferenciascom_complejo_id_f878255b_fk_core_comp; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_preferenciascomplejo
    ADD CONSTRAINT core_preferenciascom_complejo_id_f878255b_fk_core_comp FOREIGN KEY (complejo_id) REFERENCES public.core_complejo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_turno core_turno_cancha_id_209f6e0c_fk_core_cancha_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_turno
    ADD CONSTRAINT core_turno_cancha_id_209f6e0c_fk_core_cancha_id FOREIGN KEY (cancha_id) REFERENCES public.core_cancha(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_turno core_turno_cliente_id_fd853b13_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_turno
    ADD CONSTRAINT core_turno_cliente_id_fd853b13_fk_core_usuario_id FOREIGN KEY (cliente_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_turnofijo core_turnofijo_cancha_id_c67e16d2_fk_core_cancha_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_turnofijo
    ADD CONSTRAINT core_turnofijo_cancha_id_c67e16d2_fk_core_cancha_id FOREIGN KEY (cancha_id) REFERENCES public.core_cancha(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_turnofijo core_turnofijo_cliente_id_00c96fe7_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_turnofijo
    ADD CONSTRAINT core_turnofijo_cliente_id_00c96fe7_fk_core_usuario_id FOREIGN KEY (cliente_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_usuario core_usuario_complejo_id_4e2fd699_fk_core_complejo_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario
    ADD CONSTRAINT core_usuario_complejo_id_4e2fd699_fk_core_complejo_id FOREIGN KEY (complejo_id) REFERENCES public.core_complejo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_usuario_groups core_usuario_groups_group_id_55312a9a_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario_groups
    ADD CONSTRAINT core_usuario_groups_group_id_55312a9a_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_usuario_groups core_usuario_groups_usuario_id_97385234_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario_groups
    ADD CONSTRAINT core_usuario_groups_usuario_id_97385234_fk_core_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_usuario_user_permissions core_usuario_user_pe_permission_id_7f881653_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario_user_permissions
    ADD CONSTRAINT core_usuario_user_pe_permission_id_7f881653_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_usuario_user_permissions core_usuario_user_pe_usuario_id_ce4108a7_fk_core_usua; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.core_usuario_user_permissions
    ADD CONSTRAINT core_usuario_user_pe_usuario_id_ce4108a7_fk_core_usua FOREIGN KEY (usuario_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: lauri11
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_core_usuario_id FOREIGN KEY (user_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO lauri11;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO lauri11;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO lauri11;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO lauri11;


--
-- PostgreSQL database dump complete
--

\unrestrict TPq7EMbEtV5lWr9PahhCTYBKw93mykwCQUeO6cTJNCGxMzJoLjIUJPWWXmdABdC

