# Generated by Django 4.2.27 on 2025-12-24 23:20

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Rol')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono (ej: para usar con Heroicons)', max_length=50, null=True, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Característica de Cancha',
                'verbose_name_plural': 'Características de Canchas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='complejos/logos/', verbose_name='Logo')),
                ('hora_apertura', models.TimeField(default='08:00', verbose_name='Hora de apertura')),
                ('hora_cierre', models.TimeField(default='23:00', verbose_name='Hora de cierre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complejo',
                'verbose_name_plural': 'Complejos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciasComplejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primario', models.CharField(default='#3B82F6', help_text='Color en formato hexadecimal (ej: #3B82F6)', max_length=7, verbose_name='Color primario')),
                ('color_secundario', models.CharField(default='#1E40AF', max_length=7, verbose_name='Color secundario')),
                ('color_fondo', models.CharField(default='#F3F4F6', max_length=7, verbose_name='Color de fondo')),
                ('sistema_ranking', models.BooleanField(default=False, verbose_name='Sistema de ranking')),
                ('pago_senia', models.BooleanField(default=True, verbose_name='Requiere seña para reservar')),
                ('turnos_fijos_habilitados', models.BooleanField(default=True, verbose_name='Turnos fijos habilitados')),
                ('cancelacion_online', models.BooleanField(default=True, verbose_name='Cancelación online permitida')),
                ('notificaciones_whatsapp', models.BooleanField(default=False, verbose_name='Notificaciones por WhatsApp')),
                ('notificaciones_email', models.BooleanField(default=True, verbose_name='Notificaciones por Email')),
                ('tiempo_minimo_cancelacion', models.PositiveIntegerField(default=2, help_text='Horas de anticipación mínima para cancelar un turno', verbose_name='Horas mínimas para cancelar')),
                ('tiempo_maximo_reserva', models.PositiveIntegerField(default=7, help_text='Días de anticipación máxima para reservar', verbose_name='Días máximos para reservar')),
                ('complejo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='core.complejo', verbose_name='Complejo')),
            ],
            options={
                'verbose_name': 'Preferencias de Complejo',
                'verbose_name_plural': 'Preferencias de Complejos',
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cancha 1, Cancha A, etc.', max_length=50, verbose_name='Nombre')),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio por hora')),
                ('capacidad', models.PositiveIntegerField(default=4, verbose_name='Capacidad de jugadores')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='canchas/', verbose_name='Imagen')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caracteristicas', models.ManyToManyField(blank=True, related_name='canchas', to='core.caracteristicacancha', verbose_name='Características')),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='core.complejo', verbose_name='Complejo')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['complejo', 'nombre'],
                'unique_together': {('complejo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AdministradorComplejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_propietario', models.BooleanField(default=False, verbose_name='Es propietario')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.complejo', verbose_name='Complejo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Administrador de Complejo',
                'verbose_name_plural': 'Administradores de Complejos',
                'unique_together': {('usuario', 'complejo')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='complejos',
            field=models.ManyToManyField(blank=True, related_name='administradores', through='core.AdministradorComplejo', to='core.complejo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='TurnoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('fecha_inicio', models.DateField(help_text='Desde cuándo aplica el turno fijo', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Hasta cuándo aplica el turno fijo (dejar vacío para indefinido)', null=True, verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_fijos', to='core.cancha', verbose_name='Cancha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_fijos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Turno Fijo',
                'verbose_name_plural': 'Turnos Fijos',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('cancha', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='reservado', max_length=20, verbose_name='Estado')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('senia_pagada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Seña pagada')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.cancha', verbose_name='Cancha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('cancha', 'fecha', 'hora_inicio')},
            },
        ),
    ]
