# Generated by Django 4.2.27 on 2025-12-25 17:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Dejar vacío para bloquear el día completo', null=True, verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('motivo', models.CharField(help_text='Ej: Feriado, Lluvia, Mantenimiento', max_length=100, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloqueo',
                'verbose_name_plural': 'Bloqueos',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CreditoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('monto_usado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto usado')),
                ('motivo', models.CharField(help_text='Ej: Cancelación turno del 25/12/2025', max_length=200, verbose_name='Motivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crédito de Cliente',
                'verbose_name_plural': 'Créditos de Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegracionMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Token de acceso de Mercado Pago', max_length=255, verbose_name='Access Token')),
                ('public_key', models.CharField(blank=True, help_text='Clave pública (opcional, para checkout JS)', max_length=255, verbose_name='Public Key')),
                ('modo', models.CharField(choices=[('test', 'Test (Sandbox)'), ('prod', 'Producción')], default='test', max_length=10, verbose_name='Modo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('webhook_secret', models.CharField(blank=True, help_text='Secreto para validar webhooks (opcional)', max_length=100, null=True, verbose_name='Webhook Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integración Mercado Pago',
                'verbose_name_plural': 'Integraciones Mercado Pago',
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='complejos',
        ),
        migrations.AddField(
            model_name='cancha',
            name='duracion_turno_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Dejar vacío para usar la duración del complejo', null=True, verbose_name='Duración del turno (minutos)'),
        ),
        migrations.AddField(
            model_name='complejo',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único en URL (ej: padel-norte). Se genera automáticamente.', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='preferenciascomplejo',
            name='duracion_turno_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duración estándar de cada turno', verbose_name='Duración del turno (minutos)'),
        ),
        migrations.AddField(
            model_name='preferenciascomplejo',
            name='minutos_expiracion_pago',
            field=models.PositiveIntegerField(default=10, help_text='Tiempo máximo para completar el pago antes de liberar el turno', verbose_name='Minutos para completar pago'),
        ),
        migrations.AddField(
            model_name='turno',
            name='creditos_usados',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Créditos usados'),
        ),
        migrations.AddField(
            model_name='turno',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='turno',
            name='expira_en',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para completar el pago', null=True, verbose_name='Expira en'),
        ),
        migrations.AddField(
            model_name='turno',
            name='pago_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de pago'),
        ),
        migrations.AddField(
            model_name='turno',
            name='senia_requerida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Seña requerida'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complejo',
            field=models.ForeignKey(blank=True, help_text='Complejo al que pertenece (vacío para Super Administrador)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.complejo', verbose_name='Complejo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('confirmado', 'Confirmado'), ('cancelado_usuario', 'Cancelado por Usuario'), ('cancelado_admin', 'Cancelado por Admin'), ('expirado', 'Expirado')], default='pendiente_pago', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador de Complejo'), ('staff', 'Staff'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
        migrations.DeleteModel(
            name='AdministradorComplejo',
        ),
        migrations.AddField(
            model_name='integracionmercadopago',
            name='complejo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mercadopago', to='core.complejo', verbose_name='Complejo'),
        ),
        migrations.AddField(
            model_name='creditocliente',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos_clientes', to='core.complejo', verbose_name='Complejo'),
        ),
        migrations.AddField(
            model_name='creditocliente',
            name='turno_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_generados', to='core.turno', verbose_name='Turno origen'),
        ),
        migrations.AddField(
            model_name='creditocliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='bloqueo',
            name='cancha',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para bloquear todas las canchas del complejo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='core.cancha', verbose_name='Cancha'),
        ),
        migrations.AddField(
            model_name='bloqueo',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='core.complejo', verbose_name='Complejo'),
        ),
        migrations.AddField(
            model_name='bloqueo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
