# Generated by Django 4.2.27 on 2025-12-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_bloqueado_estado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bloqueo',
            index=models.Index(fields=['complejo', 'fecha'], name='bloqueo_complejo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='bloqueo',
            index=models.Index(fields=['fecha', 'cancha'], name='bloqueo_fecha_cancha_idx'),
        ),
        migrations.AddIndex(
            model_name='creditocliente',
            index=models.Index(fields=['usuario', 'complejo', 'activo'], name='credito_usuario_complejo_idx'),
        ),
        migrations.AddIndex(
            model_name='creditocliente',
            index=models.Index(fields=['activo', 'created_at'], name='credito_activo_created_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha', 'estado'], name='turno_fecha_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['cliente', 'estado'], name='turno_cliente_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha', 'hora_inicio'], name='turno_fecha_hora_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['estado', 'created_at'], name='turno_estado_created_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['cancha', 'fecha'], name='turno_cancha_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='turnofijo',
            index=models.Index(fields=['activo', 'dia_semana'], name='turnofijo_activo_dia_idx'),
        ),
        migrations.AddIndex(
            model_name='turnofijo',
            index=models.Index(fields=['cancha', 'activo'], name='turnofijo_cancha_activo_idx'),
        ),
    ]
