# Generated by Django 4.2.27 on 2025-12-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_subdominio_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='complejo',
            name='direccion_detallada',
            field=models.TextField(blank=True, help_text='Información adicional de ubicación (referencias, indicaciones, etc.)', null=True, verbose_name='Dirección Detallada'),
        ),
        migrations.AddField(
            model_name='complejo',
            name='instagram',
            field=models.CharField(blank=True, help_text='Usuario de Instagram (sin @)', max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='complejo',
            name='twitter_x',
            field=models.CharField(blank=True, help_text='Usuario de X/Twitter (sin @)', max_length=100, null=True, verbose_name='X (Twitter)'),
        ),
    ]
