# Generated by Django 4.2.27 on 2025-12-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_complejo_direccion_detallada_complejo_instagram_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('estado__in', ['cancelado_usuario', 'cancelado_admin', 'expirado']),
                    _negated=True,
                ),
                fields=('cancha', 'fecha', 'hora_inicio'),
                name='turno_cancha_fecha_hora_unico_activo',
            ),
        ),
    ]

