# Generated by Django 4.2.27 on 2026-01-11 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_turno_cancelacion_fields'),
        ('core', '0010_integracionmp_oauth_fields'),
    ]

    operations = [
    ]
