# Generated by Django 4.2.27 on 2026-01-20 18:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_turno_mp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto comisión'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='monto_senia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto seña'),
        ),
        migrations.AddField(
            model_name='preferenciascomplejo',
            name='maneja_comisiones',
            field=models.BooleanField(default=False, help_text='Si está activo, se suma la comisión configurada en cada cancha a la seña', verbose_name='Maneja comisiones'),
        ),
        migrations.AddField(
            model_name='turno',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto comisión'),
        ),
    ]
