# Generated by Django 4.2.27 on 2026-02-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_turnofijo_duracion_minutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnofijo',
            name='duracion_minutos',
        ),
    ]
