# Generated by Django 4.2.27 on 2026-02-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fix_turnofijo_duracion_column'),
        ('core', '0017_remove_turnofijo_duracion_minutos'),
    ]

    operations = [
    ]
