# Generated by Django 4.2.27 on 2026-03-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260221_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnofijo',
            name='duracion_minutos',
        ),
    ]
