# Generated by Django 4.2.27 on 2026-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_turnofijo_duracion_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('confirmado', 'Confirmado'), ('bloqueado', 'Bloqueado'), ('cancelado_usuario', 'Cancelado por Usuario'), ('cancelado_admin', 'Cancelado por Admin'), ('expirado', 'Expirado'), ('jugado', 'Jugado'), ('no_asistio', 'No Asistió')], default='pendiente_pago', max_length=20, verbose_name='Estado'),
        ),
    ]
